version: 0.2

phases:
    pre_build:
        commands:
            - echo Install packages...
            - npm install
            - echo Synchonazing database...
            - npx prisma db push
            - npx prisma migrate dev --name migration-name
    build:
        commands:
            - echo Running tests...
            - npm run test
            - echo Create build...
    post_build:
        commands:
            - echo Removing unnecessary files...
            # - rm -rf node_modules/
            # - rm -rf src/
            # - rm -rf tests/
artifacts:
    base-directory: '.'
    files:
        - '**/*'